### ISSUE TITLE
Add support for pulling Dell NetworkInterfaces

### ISSUE THREAD

**Issue by RyanW8** [stmcginnis/gofish#101]
Hey,

can we please add support for pulling network interface state etc.
NetworkAdapter
https://gist.github.com/RyanW8/b1f9e1242e601b986f903995979c32cb
NetworkDeviceFunctions
https://gist.github.com/RyanW8/becd44a9ed8ee0c7a46034899d2a0375
NetworkDeviceFunction
https://gist.github.com/RyanW8/1efa358c0c1df610f18767bc7c6a2b63

Thanks,
Ryan

**Comment by stmcginnis** [comment]
Hey @RyanW8, the NetworkAdapter (https://github.com/stmcginnis/gofish/blob/master/redfish/networkadapter.go) and NetworkDeviceFunction (https://github.com/stmcginnis/gofish/blob/master/redfish/networkdevicefunction.go) objects are defined. Is there somewhere missing to navigate to these objects?

**Comment by stmcginnis** [comment]
The Chassis object has the NetworkAdapters() call. The ComputerSystem object has NetworkInterfaces. From the NetworkInterface you can call NetworkAdapter() to get its adapter. From a NetworkAdapter you can call NetworkDeviceFunctions() to get the functions.

Hope this helps. Just let me know if there is an association missing somewhere that prevents part of this from being accessible.

Thanks!
