### ISSUE TITLE
Creation a Session does not conform to DMTF Specification

### ISSUE THREAD

**Issue by RyanW8** [stmcginnis/gofish#102]
Hey,

So we're running into a weird issue on about 20 or so SuperMicro devices where the redfish endpoint `/redfish/v1/SessionService/Sessions` is returning a 401 unauthorized (It returns a 401 even when using an admin user). This seems to be preventing a redfish client from being created. Below is the code used to create a gofish/redfish client. 

```
func newRedfishClient(host string, username string, password string) (*gofish.APIClient, error) {

	url := fmt.Sprintf("https://%s", host)

	config := gofish.ClientConfig{
		Endpoint: url,
		Username: username,
		Password: password,
		Insecure: true,
	}
	redfishClient, err := gofish.Connect(config)
	if err != nil {
		return nil, err
	}
	return redfishClient, nil
}
```

Is there any workaround?

**Comment by RyanW8** [comment]
I'd also like to add I've verified the account it's using to connect, it has the 'Administrator' role and is able to access everything else on the API.

**Comment by sungup** [comment]
Did you purchase the license named "SFT-DCMS-Single" for your supermicro server? I know that user should pay to activate the REST API features on the SuperMicro Server.

https://www.supermicro.com/en/solutions/management-software/redfish

**Comment by RyanW8** [comment]
> Hello RyanW8
> 
> Did you purchase the license named "SFT-DCMS-Single" for your supermicro server? I know that user should pay to activate the REST API features on the SuperMicro Server.
> 
> https://www.supermicro.com/en/solutions/management-software/redfish

Not sure to be honest... We'll have a look into this. Although pretty sure it isn't licensing related as when using PostMan with basic auth it seems to work okay. I've tried enabling basic auth in the application that's using this library but for some reason that shits itself so seeing if there's a different work around

**Comment by RyanW8** [comment]
For example, using this gofish ClientConfig
`
	config := gofish.ClientConfig{
		Endpoint: url,
		Username: username,
		Password: password,
		Insecure: true,
		BasicAuth: true,
	}
`

The logs of the app (https://github.com/jenningsloy318/redfish_exporter) are spammed with the following:
`
2020/12/07 12:47:30 Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>
2020/12/07 12:47:30 Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>
2020/12/07 12:47:32 Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>
`

Until it eventually crashes with 

`
panic: send on closed channel

goroutine 1054 [running]:
github.com/jenningsloy318/redfish_exporter/collector.parseEthernetInterface(0xc00055c120, 0x0, 0x0, 0xc00031cb00, 0xc0003faf04)
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:676 +0x7c5
created by github.com/jenningsloy318/redfish_exporter/collector.(*SystemCollector).Collect
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:532 +0xbdf
panic: send on closed channel

goroutine 1055 [running]:
github.com/jenningsloy318/redfish_exporter/collector.parseEthernetInterface(0xc00055c120, 0x0, 0x0, 0xc0000fc580, 0xc0003faf04)
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:672 +0xa07
created by github.com/jenningsloy318/redfish_exporter/collector.(*SystemCollector).Collect
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:532 +0xbdf
panic: send on closed channel

goroutine 1052 [running]:
github.com/jenningsloy318/redfish_exporter/collector.parseEthernetInterface(0xc00055c120, 0x0, 0x0, 0xc0004cc2c0, 0xc0003faf04)
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:672 +0xa07
created by github.com/jenningsloy318/redfish_exporter/collector.(*SystemCollector).Collect
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:532 +0xbdf
panic: send on closed channel

goroutine 1056 [running]:
github.com/jenningsloy318/redfish_exporter/collector.parseEthernetInterface(0xc00055c120, 0x0, 0x0, 0xc0000fcb00, 0xc0003faf04)
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:672 +0xa07
created by github.com/jenningsloy318/redfish_exporter/collector.(*SystemCollector).Collect
        /go/src/github.com/jenningsloy318/redfish_exporter/collector/system_collector.go:532 +0xbdf
`

**Comment by RyanW8** [comment]
Believe I've found the cause. 
https://github.com/stmcginnis/gofish/blob/master/redfish/session.go#L84 - This does not capitalize the 'n' in username. It should be 'UserName'. According to https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.11.1.pdf (14.3.3.2). This is why 20+ hosts of ours are failing to create a session. Capitalizing this would resolve this.

**Comment by stmcginnis** [comment]
Oh, interesting... good catch. I could see how some implementations would parse that case-insensitive, but others may actually care. Good thing is that should be an easy fix.

**Comment by RyanW8** [comment]
Just created a PR for it too :)

**Comment by RyanW8** [comment]
Hmmm, that seems to of fixed 6/30 hosts. Although for some reason 24 are still reporting that it cannot authenticate. Again I've performed a post in PostMan with the credentials we're using and it was successful. The correct headers & status code was returned. Did I miss something in the PR?

**Comment by RyanW8** [comment]
Found the problem. When the URI doesn't have a trailing `/` the host doesn't like it. Appending a trailing `/` to the end of the URI fixes the problem

**Comment by stmcginnis** [comment]
Glad you were able to figure it out Ryan. Any remaining issues? Or can this be closed out now?
