### ISSUE TITLE
HostedServices field in ComputerSystem doesn't match Redfish Schema

### ISSUE THREAD

**Issue by WendyMcNaughton** [stmcginnis/gofish#109]
I'm having difficulty with the redfish.GetComputerSystem() call returning the error:
    `json: cannot unmarshal object into Go struct field .HostedServices of type string`

According to the Redfish Schema for ComputerSystem, the HostedServices field is a complex type.  As such, the golang data model generated by openapi-generater from this schema defines HostedServices as follows:
```
type ComputerSystemV1130ComputerSystem struct { 
        ...
        HostedServices ComputerSystemV1130HostedServices `json:"HostedServices,omitempty"`
}

type ComputerSystemV1130HostedServices struct {
        // The OEM extension.
        Oem map[string]map[string]interface{} `json:"Oem,omitempty"`

        StorageServices OdataV4IdRef `json:"StorageServices,omitempty"`
}

```

Yet, the gofish library is attempting to unmarshal this object into a string as defined by the ComputerSystem struct:
```
type ComputerSystem struct {
...
	// HostedServices shall describe services supported by this computer system.
	HostedServices string
```

Changing the openapi-generated definition of HostedServices to a string in my Redfish API service resolves this error.  Any explanation for this mismatch?

**Comment by stmcginnis** [comment]
Thanks Wendy. There are a few properties yet that were really just placeholders at the time. HostedServices definitely is one of those cases.

According to the spec, that should be an object that links to other services. StorageServices is the only thing defined currently, along with OEM properties that we may or may not be able to host.

If you can provide a paste of the JSON output from getting ComputerSystem, I should be able to tell from that what your implementation is sending and see if we can support it. Otherwise, I can just make this a private property for now so it won't cause any harm.

**Comment by WendyMcNaughton** [comment]
Thanks, Sean for the quick response.  The funny thing is, we aren't even including the "HostedServices" field in GetComputerSystem() response since it;s omitted if empty. We are just starting our Redfish service implementation so there aren't many populated fields.

I'm curious as to why other users haven't run into this issue.

Anyway, here's a sample json (obtained via curl)  from /redfish/v1/Systems/MXQ8360404:
```
{
   "Status" : {},
   "SerialConsole" : {
      "SSH" : {},
      "Telnet" : {},
      "IPMI" : {}
   },
   "Model" : "ProLiant DL380 Gen9",
   "Processors" : {
      "@odata.id" : "/redfish/v1/Systems/MXQ8360404/Processors"
   },
   "Actions" : {
      "#ComputerSystem.RemoveResourceBlock" : {},
      "#ComputerSystem.Reset" : {},
      "#ComputerSystem.SetDefaultBootOrder" : {},
      "#ComputerSystem.AddResourceBlock" : {}
   },
   "VirtualMediaConfig" : {},
   "Manufacturer" : "HP",
   "LastResetTime" : "0001-01-01T00:00:00Z",
   "SerialNumber" : "MXQ8360404",
   "BootProgress" : {},
   "SecureBoot" : {},
   "Links" : {},
   "Bios" : {},
   "@odata.id" : "/redfish/v1/Systems/MXQ8360404",
   "FabricAdapters" : {},
   "NetworkInterfaces" : {},
   "BiosVersion" : "P89 10/21/2019",
   "MemoryDomains" : {},
   "VirtualMedia" : {},
   "HostWatchdogTimer" : {
      "FunctionEnabled" : null,
      "TimeoutAction" : "",
      "Status" : {}
   },
   "Boot" : {
      "BootOptions" : {},
      "Certificates" : {}
   },
   "GraphicalConsole" : {},
   "LogServices" : {},
   "EthernetInterfaces" : {},
   "Id" : "",
   "MemorySummary" : {
      "TotalSystemMemoryGiB" : 1536,
      "Status" : {},
      "Metrics" : {}
   },
   "HostName" : "node0.ferrari.sn.stratus.com",
   "ProcessorSummary" : {
      "Status" : {},
      "Count" : 2,
      "Model" : "Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz",
      "Metrics" : {}
   },
   "Memory" : {
      "@odata.id" : "/redfish/v1/Systems/MXQ8360404/Memory"
   },
   "SimpleStorage" : {},
   "@odata.type" : "#ComputerSystem.v1_10_0.ComputerSystem",
   "Storage" : {
      "@odata.id" : "/redfish/v1/Systems/MXQ8360404/SimpleStorage"
   },
   "Name" : ""
}
```

**Comment by stmcginnis** [comment]
Hmm, that is really odd. Yeah, I have retrieved ComputerSystem from several different vendor's servers, and there are a lot of others using this, so I have no idea why you would be hitting this and not others.

I will just "hide" the property for now and can look at completing the implementation for it at a later time.

Thanks for the details!

**Comment by WendyMcNaughton** [comment]
Thanks for making the change.  It has resolved my issue.
