### ISSUE TITLE
Local channel connection?

### ISSUE THREAD

**Issue by mpictor** [stmcginnis/gofish#119]
Using this lib, is it possible to connect to the local BMC without a network connection? For example, ilorest uses `ilorest_chif.so` to communicate without need for an IP.

If not implemented, any thoughts on how difficult it'd be? I've not seen specs for how HPE communicates, though I'm not sure whether that's because it is proprietary or if I merely haven't looked hard enough.

**Comment by stmcginnis** [comment]
Hey Mark. Conceivable that could work. Everything is run through the client object, so if we know how ilorest_chif.so is performing that communication, we could have a client that performs the calls through that protocol instead.

I don't know anything about it though. I have a suspicion that it is maybe a proprietary interface that they don't publicly document. If you are able to find out any technical details about how that works, we definitely could look at adding it. I'm not set up to be able to test any implementation, but we could add the bits and treat it as an "alpha" functionality until we can get feedback from folks actually using it against a real system.

**Comment by stmcginnis** [comment]
Closing this for now. Happy to reopen and/or accept PRs if someone knows how the handle that communication.
