### ISSUE TITLE
Error when creating a user using ManagerAccount

### ISSUE THREAD

**Issue by ftenario** [stmcginnis/gofish#124]
Hi Sean,

I tried creating a user using ManagerAccount and I got an error. Here is the code
```
func main() {
  config := gosih.ClientConfig{
    Endpoint: "BMC_IP",
    Username: "username",
    Password: "password",
    Insecure: true,
  }

  c, _ := gofish.Connect(config)
  defer c.Logout()

  mgr := &redfish.ManagerAccount{
    UserName: "new user",
    Password: "password",
    Enabled: true,
    RoleID: "Administrator",
  }
  mgr.ODataID = "/redfish/v1/AccoutService/Accounts/3"
  mgr.SetClient(c)

  if err := mgr.Update(); err != nil {
    fmt.Println("Error:", err)
  }
}
```

Error is "RoleID field is read only". It turns out, it will fail here https://github.com/stmcginnis/gofish/blob/main/redfish/manageraccount.go#L137 during comparison at https://github.com/stmcginnis/gofish/blob/main/common/types.go#L82

"RoleId" should be "RoleID". 
I can create a PR for this and add a test if it is Ok with you.

regards,
Ferdinand

**Comment by stmcginnis** [comment]
Hey @ftenario, thanks for taking a look at this.

There's actually https://github.com/stmcginnis/gofish/issues/72 to get this capability added. The Update() call was really meant for making updates to existing objects retrieved from the service.

That said, if this works until a better mechanism is implemented, that's great. You are correct - that appears to be a bug that the update check is using different casing than the actual object property. If you make that change and it works for what you are doing, a PR to update that would be welcome.

Thanks!

**Comment by ftenario** [comment]
Hi @stmcginnis,
Sorry it took me longer to respond. Do you need to grant me access to be able to push a branch?

thanks!

**Comment by stmcginnis** [comment]
Sorry I didn't see your question until now. You would create a fork and push your changes to there, then create a PR from your fork to this repo.

I have a fix for this now, but would really appreciate any other proposals. Thanks!
