### ISSUE TITLE
Tag v0.9.0 version

### ISSUE THREAD

**Issue by mikeletux** [stmcginnis/gofish#128]
Hi Sean,

Could you please tag main branch with v0.9.0 please?

It's been implemented new features I'd like since two months ago. I'd really appreciate it 😄 

Have a nice day!
/Miguel

**Comment by mikeletux** [comment]
Many thanks @stmcginnis for you support and quick responses as always!

Have a great day!

**Comment by stmcginnis** [comment]
And done - https://github.com/stmcginnis/gofish/releases/tag/v0.9.0

Thanks!
