### ISSUE TITLE
Possible to add a new release with current code?

### ISSUE THREAD

**Issue by grantcurell** [stmcginnis/gofish#148]
I'm working on a project leveraging code from some of the more recent commits not included in the 9.0 code. Problem is people get `service.Entity.Client.PostMultipartWithHeaders undefined` unless we fix a specific commit in go mod or tell people to pull a specific version. Does it happen to be on the timeline to do a minor release with a label soon?

Edit: Nvm I spoke to soon. Posted this based on a problem from last week and just saw that there is a new release and now feel dumb.

**Comment by stmcginnis** [comment]
Hopefully this works for you. Just pointing out you can do `go get github.com/stmcginnis/gofish@[commit hash]` to use the latest code. But if it helps having a new official release out there, just let me know.

**Comment by grantcurell** [comment]
Nope! We're good - that's what we were doing internally. I was just bad and didn't even notice you had already posted 10.0 😂

**Comment by grantcurell** [comment]
I appreciate the help though - apologies for needlessly bothering you. I appreciate your maintenance of the gofish library!
