### ISSUE TITLE
Stary prints in v0.10.0 release, it is flooding  logs 

### ISSUE THREAD

**Issue by sanverm2** [stmcginnis/gofish#149]
We are seeing stray prints in the logs . Please remove them it is flooding the logs. 

Fille:  redfish/chassis.go:272:	fmt.Printf("+++++ Drives: %v\n", t.Drives) 

```
+++++ Drives: 
+++++ Drives: 
+++++ Drives: 
+++++ Drives: 

```

**Comment by sanverm2** [comment]
@stmcginnis .

**Comment by stmcginnis** [comment]
Hi sanverm2, these have already been removed. Please update your go.mod to point to a newer version.
