### ISSUE TITLE
X-Auth-Token need CSRFToken

### ISSUE THREAD

**Issue by admover** [stmcginnis/gofish#157]
Hi.
  When I use it for Inspur, it's return "panic: 401: { "cc": 7, "error": "Invalid Authentication" }", please help me!

Postman:
-Create session：https://192.168.1.1/redfish/v1/SessionService/Sessions
-Response:
`{
    "default_passwd": 0,
    "ResidueDay": 255,
    "ok": 0,
    "privilege": 4,
    "extendedpriv": 259,
    "racsession_id": 50,
    "remote_addr": "192.168.1.2",
    "server_name": "192.168.1.1",
    "server_addr": "192.168.1.1",
    "HTTPSEnabled": 1,
    "CSRFToken": "Ydom4LCh",
    "Id": "509103346d39ead083Q3wDT6xjK8UqYdom4LCh"
}`
X-Auth-Token: 509103346d39ead083Q3wDT6xjK8UqYdom4LCh
Location: /redfish/v1/SessionService/Sessions/509103346d39ead083Q3wDT6xjK8Uq

**Comment by stmcginnis** [comment]
Hey @admover - I've never run against an Inspur device. Is it possible you need to enable different authentication methods? Looks like maybe it doesn't have the default auth enabled?

**Comment by admover** [comment]
Thank you, I will try.

**Comment by admover** [comment]
It's ok when i used in Postman.

======================= Inspur=====================
Response header:<img width="1031" alt="image" src="https://user-images.githubusercontent.com/8574628/130714266-503e1d8e-7f58-40b1-a912-97c817a1e361.png">
Response body:<img width="1029" alt="image" src="https://user-images.githubusercontent.com/8574628/130714669-fc1bd7d0-60a6-406b-8d47-701ba1e5038c.png">
Get sessions:<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8574628/130714315-b9c93660-34c2-4099-88eb-815d10f1ce61.png">

=======================HP=======================

Response header:<img width="1037" alt="image" src="https://user-images.githubusercontent.com/8574628/130714335-56f638c3-2d67-423b-a7bd-3240686c878d.png">
Response body:<img width="1033" alt="image" src="https://user-images.githubusercontent.com/8574628/130714685-627ad68e-41a2-43a7-b859-4dbdf6122bc4.png">
Get sessions:<img width="1033" alt="image" src="https://user-images.githubusercontent.com/8574628/130714354-6be6b7dd-0ee1-48b6-a2b3-0a242fcf6e3a.png">

**Comment by admover** [comment]
If I open the redfish api for you, can you check why?

**Comment by stmcginnis** [comment]
Thanks @admover. If I had access I can confirm what you've already posted above.

**Comment by admover** [comment]
Can you tell me your public IP? I need to configure the firewall access list.

**Comment by stmcginnis** [comment]
Sorry, I don't have a public static IP address.

**Comment by admover** [comment]
Okay, please tell me your email and I will send you the authentication information.

**Comment by stmcginnis** [comment]
You can send it to sean.mcginnis@gmail.com

**Comment by stmcginnis** [comment]
I have confirmed I get the same response you were seeing. Rather than sending a valid `Session` object back from the login, the Inpur devices is returning a non-standard JSON struct:

```json
{ "default_passwd": 0, "ResidueDay": 255, "ok": 0, "privilege": 4, "extendedpriv": 256, "racsession_id": 6, "remote_addr": "72.50.207.44", "server_name": "116.239.7.117", "server_addr": "192.168.30.85", "HTTPSEnabled": 1, "CSRFToken": "rykXBkIm", "Id": "ecd10d18c6066bf79bkAylQAxrxQl1rykXBkIm" }
```

And there is no `CSRFToken` in the response headers:

```
X-Xss-Protection : [1; mode=block]
Location : [/redfish/v1/SessionService/Sessions/ecd10d18c6066bf79bkAylQAxrxQl1]
X-Auth-Token : [ecd10d18c6066bf79bkAylQAxrxQl1rykXBkIm]
Content-Type : [application/json]
Set-Cookie : [QSESSIONID=ecd10d18c6066bf79bkAylQAxrxQl1; path=/; secure;HttpOnly]
Date : [Mon, 30 Aug 2021 17:43:35 GMT]
X-Content-Type-Options : [nosniff]
Strict-Transport-Security : [max-age=31536000; includeSubDomains]
Content-Security-Policy : [default-src 'none'; child-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self'; object-src 'self'; style-src 'self' 'unsafe-inline']
X-Frame-Options : [SAMEORIGIN]
```

So this confirms they are not following the Redfish spec. If the CSRFToken is needed to be passed along in subsequent calls, they would need to change that to be returned in the response headers. If that is done, gofish could be updated to look for that in the headers and store it to pass back in authenticated calls like what is done with things like `X-Auth-Token`.

If you have a support contract for this hardware, I would recommend opening a support ticket with Inspur and raising this as an issue. They are not following the Redfish specification, so they need to review the spec and correct their implementation.

**Comment by stmcginnis** [comment]
For their reference, the session login is detailed in section 15.3.4.2 in the spec available here: https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.13.0.pdf

Going to close this issue as it is not something wrong in the gofish client. Feel free to reopen or file a new issue if Inspur is able to correct their implementation and we can take a look at adding custom CSRFToken handling, as long as it can be done in a way that will not cause issues with spec-conforming implementations.

**Comment by admover** [comment]
Thank you for your help.

**Comment by admover** [comment]
`req.Header.Set("Cookie", fmt.Sprintf("sessionKey=%s", c.auth.Token))`
I found the problem
If the authentication is passed, the program will add a cookie as "sessionKey= XXXXXXXXXXXXXXXXXXXXXX"
But the cookie returned by the device is "QSESSIONID=XXXXXXXXXXXXXXXXXXXXXX"
I commented out this line and the program is running.
But it return other panic when use `service.Sessions()`, i'm sad.
`panic: failed to retrieve some items: [{"link":"3a9808670d509ccaf91Sh62LqBxSIt","error":"invalid character '\\x1f' looking for beginning of value"}]`
