### ISSUE TITLE
Request to add Name filed into the resources 

### ISSUE THREAD

**Issue by jenningsloy318** [stmcginnis/gofish#16]
Hi,

I am ultilizing this lib to construct a prometheus monitoring exporter, so lables with component Name is a good one to distinguish them. but resources such as `Memory`, `drive` `volume` ,`PCIeDevice`, `Ethernetinterfaces` ... etc. seems don't have `Name` field,  and it is essential to have thie field to distinguish different type /name of the resource when getting the metrics. 

Is there any concerns to add this filed ?

**Comment by stmcginnis** [comment]
These objects inherit the common.Entity type, so they all have a Name property.

https://github.com/stmcginnis/gofish/blob/master/school/common/types.go#L37

**Comment by jenningsloy318** [comment]
@stmcginnis I noticed this ,similar to `Status`, but this `common.Entity` is not exported as `Status`

**Comment by stmcginnis** [comment]
Maybe this will help: https://golangbot.com/inheritance/

The objects "inherit" from common.Entity. It's not like common.Status that is a type that gets exposed as a property of the new struct.

**Comment by stmcginnis** [comment]
Here is a usage example that may help:

`
package main

import (
	"fmt"

	gofish "github.com/stmcginnis/gofish/school"
)

func main() {
	c, _ := gofish.APIClient("http://localhost:5000", nil)
	service, _ := gofish.ServiceRoot(c)

	systems, _ := service.Systems()
	for _, system := range systems {
		fmt.Printf("System '%s' memory:", system.Name)
		memory, _ := system.Memory()
		for _, mem := range memory {
			fmt.Printf("\t Memory name: %s\n", mem.Name)
		}
	}
}
`

Note that if using the Redfish-API-Emulator, there currently is a bug in the emulated objects that causes JSON parsing issues with Memory objects. If you wanted to test against that, you will need to pull in the changes from https://github.com/DMTF/Redfish-Interface-Emulator/pull/77.
