### ISSUE TITLE
Fetch collection members in parallel

### ISSUE THREAD

**Issue by nrolans** [stmcginnis/gofish#160]
I experimented with this idea in https://github.com/nrolans/gofish/commit/85f27a13ac3b528eeef7547593f31158b81c4779

With just two go routines in parallel, the speed up is already noticeable in the firmware inventory.

* Dell R740 with 46 images: 38s to 26s
* Dell R730 with 19 images: 1:58 to 1:13

Is this of interest? If so I can continue this work.

**Comment by stmcginnis** [comment]
I believe this has been implemented, but feel free to propose any further updates if needed. Thanks!
