### ISSUE TITLE
unable to execute request, no target provided，the session/url is nil

### ISSUE THREAD

**Issue by dazhaoyu** [stmcginnis/gofish#162]
hi, I used this gofish tool,  base on the example, when I set endpoint\username\password value, in session.go. line 82, the CreateSession function, the uri is nil, so it throw "unable to execute request, no target provided" error. pls help, thanks!

**Comment by stmcginnis** [comment]
Hi @dazhaoyu! Can you provide a snippet of your code to show how you are connecting? It should be something similar to the code in https://github.com/stmcginnis/gofish/blob/main/examples/query_sessions.md

After connecting to the Redfish host, it queries the `ServiceRoot` of the Redfish service to link to nearly all other things. That `ServiceRoot` object returned by the service should contain relative links to other objects hosted by the service. If there is an issue with the Redfish implementation where it is not returning those links, that could cause the behavior seen as well. Can you try going to the Redfish service endpoint in a web browser or by using something like `curl` to get the JSON response it provides? If you are able to post that here, I can take a look and make sure it looks legitimate.

**Comment by dazhaoyu** [comment]
hello @stmcginnis , yes, my code just as same as https://github.com/stmcginnis/gofish/blob/main/examples/query_sessions.md, create main.go file, and copy the code,  changed the config info: Endpoint, Username, Password, and Insecure is true. And then run it, it would got the "unable to execute request, no target provided" panic. If use curl like : 
`curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/SessionService/Sessions -d  '{"UserName": "Administrator", "Password": "weishi@123"}'`
 it would return statusOK, the returned headers.txt content is below:
**_HTTP/1.1 201 Created
Date: Fri, 07 Jan 2022 01:43:55 GMT
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self'; object-src 'self'; style-src 'self' 'unsafe-inline'
OData-Version: 4.0
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Location: /redfish/v1/SessionService/Sessions/842b0188dd94486f
X-Auth-Token: 76e7a2c497ce8a55af2430ade2564a7b
ETag: W/"6fa43d79"
Content-Length: 468
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Expires: 0
Content-Type: application/json;charset=utf-8_**

**Comment by stmcginnis** [comment]
That was my suspicion. Can you post the output from curling the Redfish service endpoint? My guess is the service is not returning the expected link URL and that would show us.

`curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/`

**Comment by dazhaoyu** [comment]
`curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/` would return 
HTTP/1.1 401 Unauthorized
Date: Fri, 07 Jan 2022 16:06:11 GMT
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self'; object-src 'self'; style-src 'self' 'unsafe-inline'
OData-Version: 4.0
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Length: 475
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Expires: 0
Content-Type: application/json;charset=utf-8

**Comment by stmcginnis** [comment]
Then `curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/ -d '{"UserName": "Administrator", "Password": "xxxxxxx"}'`

**Comment by dazhaoyu** [comment]
it would returned the same error info
















At 2022-01-08 00:09:40, "Sean McGinnis" ***@***.***> wrote:

Then curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/ -d '{"UserName": "Administrator", "Password": "xxxxxxx"}'

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dazhaoyu** [comment]
curl --insecure -H "Content-Type: application/json" -D headers.txt -X POST https://10.4.83.10/redfish/v1/ -d '{"UserName": "Administrator", "Password": "xxxxxxx"}' will return the below error message：
{"error":{"code":"Base.1.0.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information.","@Message.ExtendedInfo":[{"@odata.type":"\/redfish\/v1\/$metadata#MessageRegistry.1.0.0.MessageRegistry","MessageId":"Base.1.0.NoValidSession","RelatedProperties":[],"Message":"There is no valid session established with the implementation.","MessageArgs":[],"Severity":"Critical","Resolution":"Establish as session before attempting any operations."}]}}

**Comment by stmcginnis** [comment]
OK, that appears to be the problem. The Redfish implementation on the system you are trying to connect to appears to be broken. You should be able to make an unauthenticated GET call against the Redfish service endpoint. That is needed to get the reference to know where to POST to create a new session.

I would suggest checking if your vendor has a firmware update that might include fixes in their implementation.

**Comment by dazhaoyu** [comment]
after update firmware, the issue has been fixed

**Comment by stmcginnis** [comment]
Awesome, that's great to hear @dazhaoyu! Thanks for letting me know.
