### ISSUE TITLE
SetBoot fails

### ISSUE THREAD

**Issue by jasmeer** [stmcginnis/gofish#171]
SetBoot fails in Lenovo ThinkSystem SR655 (AMD processor) with error:

`{"error":{"@Message.ExtendedInfo":[{"@odata.type":"#Message.v1_0_7.Message","Message":"The request did not provide the required precondition, such as an If-Match or If-None-Match header.","MessageId":"Ami.1.0.PreconditionHeaderMissing","Resolution":"Include the required precondition header in the request","Severity":"Critical"}],"code":"Ami.1.0.PreconditionHeaderMissing","message":"The request did not provide the required precondition, such as an If-Match or If-None-Match header."} `

This is what I used as Boot param
```
redfish.Boot{
			BootSourceOverrideTarget:  redfish.BiosSetupBootSourceOverrideTarget,
			BootSourceOverrideEnabled: redfish.OnceBootSourceOverrideEnabled,
		}
```

The same works in many other platforms including Lenovo systems that use Intel processors. AMD processor systems use Redfish implementation 'AMI Redfish Server'.

Any help will be appreciated.

Thanks
Jasmeer

**Comment by stmcginnis** [comment]
Hmm, that requirement isn't part of the redfish spec, so it looks like something Lenovo specific. Since you say this works on other Lenovo systems, can you check if the firmware maybe needs to be updated on that system to see if there's a newer redfish service that might have changed this?

**Comment by jasmeer** [comment]
Thanks. I will check with Lenovo. 
Here is a doc I found about Redfish on these systems:
[Lenovo AMD 1P SR635/655 BMC Redfish RESTful API Reference](https://thinksystem.lenovofiles.com/help/topic/7Y00/rest_api_std/bmc_redfish_api_reference_sr635_sr655_standard.pdf). In page 15 it has a table that talks about precondition headers for PUT and PATCH.

**Comment by stmcginnis** [comment]
Reading through parts of the spec again, that is a supported option. Headers retrieved in the GET for an object can be used to pass to the PUT or POST. I will have to think about how we can support this.

Still would be interesting to see if the failing Lenovo server is newer or older than the ones that do work. If it is running an older version that can be upgraded, then that makes things easier. If it is newer and this is something that Lenovo now enforces in their Redfish service, that makes this a little more critical.

**Comment by jasmeer** [comment]
I tested with latest BMC version and it failed the same way.

- Build Date Jan 21 2022
- Firmware version 4.97.0

Any idea what header it is expecting? 
Thanks
Jasmeer

**Comment by stmcginnis** [comment]
Let me know if this is something you would like to take on. Otherwise I will try to put up something soon. I may be able to get to it later today, in which case I'm guessing you won't have a chance to respond, but if I do it would be great if you could test that the change works on you system since I don't have the resources locally to test this.

**Comment by jasmeer** [comment]
I can test this only next week. I will  send an update once it is done.

Thanks
Jasmeer


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
