### ISSUE TITLE
How to download service data

### ISSUE THREAD

**Issue by swahpy** [stmcginnis/gofish#203]
Hi there, I tried to figure out how to download service datat via this package, like XCC logs from lenovo xclarity system, but I didn't find anything. Could you tell me that whether or not I could do that via this package? Thank you in advance.

**Comment by Hywfred** [comment]
> I'm not familiar with Lenovo's XCC logs, but if they are standard logs I believe you would use the [LogService](https://github.com/stmcginnis/gofish/blob/main/redfish/logservice.go) to access them.
> 
> If this service data is something specific to Lenovo, then it may be possible this is something you need to use a custom OEM action to access. If that is the case, someone would need to implement an OEM handler to get that in gofish.
> 
> Maybe someone with more experience with Lenovo systems can add to this.

Yes, I think service data is something specific to lenovo, just like AHS for HPE. So this needs to be implemented by someone else. Thank you for your information.
