### ISSUE TITLE
Prep v0.14.0 release

### ISSUE THREAD

**Issue by stmcginnis** [stmcginnis/gofish#207]
It's been awhile since I've tagged an official release of the library. Putting this issue out there as a heads up that I plan to tag a `v0.14.0` soon unless there ends up being any reason to hold off.

We only have a couple open PRs that have merge conflicts and are for improved testing. There are several open issues, but _most_ of those appear to be either OEM or non-conformance to the Redfish spec, so I don't think there are any immediate actions we can take there.

Please comment here if there are any major concerns you feel should be addressed before I tag the next release.

Or course, we can always tag a `v0.15.0` if something else does come up after we tag. ;)

**Comment by stmcginnis** [comment]
Here's the diff of the commits to `main` since the last release: https://github.com/stmcginnis/gofish/compare/v0.13.0...main

**Comment by pallasscat** [comment]
@stmcginnis please add PR #211

**Comment by stmcginnis** [comment]
New release has been tagged. Thanks everyone!
