### ISSUE TITLE
Retrieving LLDP information

### ISSUE THREAD

**Issue by rohitmahadevan** [stmcginnis/gofish#250]
This is more of a question. 
It looks like the newer version of redfish allows fetching of LLDP information for NetworkAdapters. I understand that currently this library does not support but I am wondering if there are any alternatives for me to retrieve the same. 
Certain dell iDrac versions show the LLDP information under "Network Switch Connection View" tab. 

Thank you

**Comment by rohitmahadevan** [comment]
Understood. Thank you! I will have a look.

**Comment by stmcginnis** [comment]
Well, it took a full year, but I finally got around to doing that refresh... :/

I believe this has been picked up by the update to the 2023.3 bundle, so I'm going to close this. If there is something still missing, please feel free to reopen or file a new issue/PR. Thanks!
