### ISSUE TITLE
Usage of one time usable token in client config

### ISSUE THREAD

**Issue by harshitha-reddy23** [stmcginnis/gofish#258]
can u explain how the token is used, is it creating a session for token ?

**Comment by stmcginnis** [comment]
Hi @harshitha-reddy23 - yes, when connecting to a Redfish service, the connection is authenticated with either basic credentials or a session token. That token is used to track which session the client is so subsequent API calls know who the caller is.

You can see how some of that session initialization is performed here: https://github.com/stmcginnis/gofish/blob/main/client.go#L165
