### ISSUE TITLE
Compatibility concern when adding HttpBootUri type

### ISSUE THREAD

**Issue by lzap** [stmcginnis/gofish#259]
Hello,

I would like to contribute the following field:

```xml
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="ComputerSystem.v1_9_0">
      <Annotation Term="Redfish.OwningEntity" String="DMTF"/>
      <Annotation Term="Redfish.Release" String="2019.3"/>

      <EntityType Name="ComputerSystem" BaseType="ComputerSystem.v1_8_0.ComputerSystem"/>

      <ComplexType Name="Boot" BaseType="ComputerSystem.v1_7_0.Boot">
        <Property Name="HttpBootUri" Type="Edm.String">
          <Annotation Term="OData.Permissions" EnumMember="OData.Permission/ReadWrite"/>
          <Annotation Term="OData.Description" String="The URI to boot from when BootSourceOverrideTarget is set to `UefiHttp`."/>
          <Annotation Term="OData.LongDescription" String="This property shall contain the URI to perform an HTTP or HTTPS boot when BootSourceOverrideTarget is set to `UefiHttp`.  If this property is not configured or supported, the URI shall be provided by a DHCP server as specified by the UEFI Specification."/>
          <Annotation Term="OData.IsURL"/>
        </Property>
      </ComplexType>
    </Schema>
```

So from a brief read I understand that I can simply add this field to the ComputerSystem type. I also see unit tests, that is easy to.

My main question is how to handle compatibility, this flag was added in more recent versions of the schema. What is the approach you take.

Thanks for hints.

_Edited, added compatibility concern._

**Comment by lzap** [comment]
Any hints @stmcginnis ? Thanks.

**Comment by stmcginnis** [comment]
Don't know how I missed this coming in - sorry about that!

So far, for newer properties and methods in the schema, we've mostly just been adding them and expecting the consumer of the library to handle the error if the attempt fails or the value is missing.

Thanks for looking at this! Contributions would definitely be appreciated.

Not sure if it would be more work for this one targeted update, but there is a [script under tools](https://github.com/stmcginnis/gofish/blob/main/tools/generate_from_schema.py) that can be used to generate source from the schema. It doesn't generate the unit tests, but could be an easy diff to copy out the generated code and paste part of it into the source code.

**Comment by lzap** [comment]
Thanks, created https://github.com/stmcginnis/gofish/pull/271

There is no simulator that supports this relatively new flag, at least no I am aware of. Need to test this on real hardware.
