### ISSUE TITLE
Type errors and missing items

### ISSUE THREAD

**Issue by jenningsloy318** [stmcginnis/gofish#28]
Hi,

from real test, found found type errors
1. power votage type error, most of them are `float` not `int`, so need to change to `float32`
2. power metrcs also are float for watts, so also need to change to `float32`
3. Redundancy. RedundancySet should be `common.Links` not string 
4.  not sure why `common.Entity`  is removed from `chassis` objects, such as temperature/fan/power....

**Comment by stmcginnis** [comment]
Thanks @jenningsloy318. I need to set up a more thorough functional test to catch these better.
