### ISSUE TITLE
Looking for NetworkProtocol support

### ISSUE THREAD

**Issue by pruthvitd** [stmcginnis/gofish#288]
We are looking for NetworkProtocol support, we could find it in the Pull Request https://github.com/stmcginnis/gofish/pull/242
but not in https://pkg.go.dev/github.com/stmcginnis/gofish@v0.14.0
Need your help on this please.

**Comment by stmcginnis** [comment]
Hi @pruthvitd. I haven't done a release since right before that was added. I can tag another release, but you can also grab from the latest sha.

I'll tag the release now since there are a few things that have gone in that would be nice to get tagged.

**Comment by stmcginnis** [comment]
The [v0.15.0 release](https://github.com/stmcginnis/gofish/releases/tag/v0.15.0) has been tagged. If you update to that version, you should see the updated NetworkProtocol bits.
