### ISSUE TITLE
Default Paths are not respected by different vendors

### ISSUE THREAD

**Issue by ncode** [stmcginnis/gofish#3]
Hello @stmcginnis, 

I've started running the gofish against all of our vendors and I found out (sadly but kinda expected) that they don't respect the "Default.*Path". So we would need to update the values that are constants today to become variables, or stick to the "ListReferenced.*" to retrieve all objects that you are doing already. I've started working the second approach, so I would like to double check if you agree with that. 

I've added to screenshots that reflect that on the session path, but I'm also seeing it against other paths.

![Sessions](https://user-images.githubusercontent.com/52380/61052712-3e0a9100-a3ec-11e9-84dd-b2bc9e1dce89.png)
![SessionServiceSessions](https://user-images.githubusercontent.com/52380/61052723-4367db80-a3ec-11e9-89aa-e2bfd4885054.png)

**Comment by stmcginnis** [comment]
I think the spec only guarantees that the ServiceRoot is at a set location. The rest of the entities need to be navigated to from there. I added the default paths as a kind of convenience, but I think you are right that they really aren't of much use.

So I think you are using the right approach by using ListReferenced. That's probably the only consistent way to get to the right paths across different implementations.

**Comment by ncode** [comment]
Yeap. I also found it convenient :). I will work with that in mind. Thanks!
