### ISSUE TITLE
Missing common.Entity in PowerInfoVoltage and PowerSupply in redfish module

### ISSUE THREAD

**Issue by jenningsloy318** [stmcginnis/gofish#30]
Hi,

Still find that common.Entity is missing in chassis PowerSupply and PowerInfoVoltage in redfish module

Can you please help check all objects if missing it as well.

Thanks.

**Comment by stmcginnis** [comment]
OK, I fixed up all of the power related EntityTypes, and a spot check of some of the other classes didn't find any other issues.
