### ISSUE TITLE
Ports/NetworkPorts are not LinksCollection

### ISSUE THREAD

**Issue by smiller248** [stmcginnis/gofish#328]

**Comment by stmcginnis** [comment]
Can you give a little more context on this?

Ports are accessed via a few different objects. Looking at the `EthernetInterface` definition, the ports there are defined as an array of links, versus a collection that you query to get the array of links as Members of the collection.

There may be other paths to get them, so it's possible it's defined differently elsewhere. If you could point me to where you are trying to get them, or a sample snippet of code, I can take a closer look.

**Comment by smiller248** [comment]
Closing this issue, please see https://github.com/stmcginnis/gofish/pull/329.
