### ISSUE TITLE
Wrong PowerControl argument type on Outlet

### ISSUE THREAD

**Issue by Arno500** [stmcginnis/gofish#339]
Hi there!

Just wanted to raise that the current type used for PowerControl is wrong: it is currently a "PowerState" (from computersystem), but it should be a PowerState from the circuit which should only allow "On", "Off", and "PowerCycle".
See: 
- https://redfish.dmtf.org/schemas/v1/Outlet.v1_4_2.json line 602
- Redirecting to https://redfish.dmtf.org/schemas/v1/Circuit.json#/definitions/PowerState line 311

Thanks!

**Comment by stmcginnis** [comment]
Thanks for pointing that out @Arno500 - good catch! I will update it shortly.
