### ISSUE TITLE
Unmarshalling error for Operating System

### ISSUE THREAD

**Issue by nyameen** [stmcginnis/gofish#364]
Hello. I am trying to obtain Operating System information from a server. However, I get the following error.

`failed to retrieve some items: [{"link":"/redfish/v1/Systems/437XR1138R2","error":"json: cannot unmarshal object into Go struct field .OperatingSystem of type string"}]`

I am using the [DMTF Redfish Mockup Server](https://github.com/DMTF/Redfish-Mockup-Server) with the following [schema](https://github.com/DMTF/Redfish-Publications/tree/main/mockups/public-applications)

```bash
python3 redfishMockupServer.py -D ~/Redfish-Publications/mockups/public-applications/ -S
```

This is the following code snippet that produces the error, (disregard proper error handling)

```golang
package main

import (
	"fmt"

	"github.com/stmcginnis/gofish"
)

func main() {
	cli, err := gofish.ConnectDefault("http://localhost:8000")
	if err != nil {
		fmt.Println("Error: ", err)
		return
	}
	defer cli.Logout()

	chassis, _ := cli.GetService().Chassis()

	for _, c := range chassis {
		comps, err := c.ComputerSystems()
		if err != nil {
			fmt.Println("Error computer systems: ", err)
			continue
		}
                // does not get here
		for _, comp := range comps {
			fmt.Println("Operating System: ", comp.OperatingSystem)
		}
	}
}
```

The same error occurs with this snippet as well.
```golang
func main() {
	cli, err := gofish.ConnectDefault("http://localhost:8000")
	if err != nil {
		fmt.Println("Error: ", err)
		return
	}
	defer cli.Logout()

	_, err = cli.GetService().Systems()
	if err != nil {
		fmt.Println("Error: ", err)
		return
	}
}
```
Any help would be greatly appreciated!

**Comment by nyameen** [comment]
Hi @stmcginnis, are you able to look at this by any chance? No rush. 😃

**Comment by stmcginnis** [comment]
Sorry about that, I totally missed this coming in.

It does indeed look like the property is not defined correctly. Luckily a pretty minor mismatch. PR coming shortly.

**Comment by nyameen** [comment]
@stmcginnis Thank you!
