### ISSUE TITLE
[gofish@v0.19.0] [go1.18.5] Not backward-compatible with older versions of Go

### ISSUE THREAD

**Issue by thinhngotony** [stmcginnis/gofish#370]
For older Go versions, it will have the issue like below

`/go/pkg/mod/github.com/stmcginnis/gofish@v0.19.0/common/entity.go:277:9: cannot use entity (variable of type PT constrained by interface{*T; SchemaObject}) as type *T in return statement: #20 14.72 	PT does not implement *T (type *T is pointer to interface)`

**Comment by stmcginnis** [comment]
That is correct, Gofish does not support [older EOL versions of Go](https://endoflife.date/go) due to use of newer generics. You will need to use [Go 1.21](https://github.com/stmcginnis/gofish/blob/main/go.mod#L3) or newer.
