### ISSUE TITLE
Cannot access Environment Metrics for Drives 

### ISSUE THREAD

**Issue by simranjl** [stmcginnis/gofish#371]
Hello,
I'm facing an issue while attempting to access environment metrics for the Drive resource. It seems that there isn't an EnvironmentMetrics() function available for this resource. The only way to potentially access it is to obtain the value of the environmentMetrics key in the Drive struct and pass the link to the GetEnvironmentMetrics() function. Unfortunately, the 'environmentMetrics' in the struct is not an exported variable, making it inaccessible as well. I would greatly appreciate any assistance with resolving this issue. Thank you for your help!

**Comment by stmcginnis** [comment]
It looks like `EnvironmentMetrics()` just hasn't been added yet. I can try to get to that shortly. Just need to wrap up some current work, so it hopefully shouldn't be too long.

**Comment by simranjl** [comment]
Sounds good. Thank you!

**Comment by stmcginnis** [comment]
Should now be able to `go get github.com/stmcginnis/gofish@0cb0c9cbe86fca8efd4d258d837f9cd7dff28f05` to get access to this.
