### ISSUE TITLE
Unable to list BIOS attributes?

### ISSUE THREAD

**Issue by goldyfruit** [stmcginnis/gofish#49]
Hi guys,

I'm trying to list BIOS attribute but it seems that I'm missing something.

```
	config := gofish.ClientConfig{
		Endpoint: "https://" + credentials.DriverInfo.IpmiAddress,
		Username: credentials.DriverInfo.IpmiUsername,
		Password: credentials.DriverInfo.IpmiPassword,
		Insecure: true,
	}
	c, err := gofish.Connect(config)
	if err != nil {
		fmt.Print(err)
	}
	service := c.Service
	systems, _ := service.Systems()

	for _, system := range systems {
		bios, _ := system.Bios()
		fmt.Print(bios)
	}
```
I got this output but no attributes.
```
&{{Bios BIOS Configuration Current Settings 0xc000dc6870} /redfish/v1/$metadata#Bios.Bios  /redfish/v1/Systems/System.Embedded.1/Bios #Bios.v1_0_2.Bios BiosAttributeRegistry.v1_0_0 BIOS Configuration Current Settings /redfish/v1/Systems/System.Embedded.1/Bios/Actions/Bios.ChangePassword /redfish/v1/Systems/System.Embedded.1/Bios/Actions/Bios.ResetBios}
```
How can I display the content of `BIOS Configuration Current Settings` ?
Using a simple `curl` display what I expect.

**Comment by stmcginnis** [comment]
This is one area I need to address yet. The attributes are a loose set of typed values, so I just need to think about how best to handle this with go.

I'm actually hoping to spend some time on gofish today, so hopefully I will have an update that addresses this soon.

**Comment by goldyfruit** [comment]
@stmcginnis There is no rush, until then I'll use Ansible to collect these information.
Thanks!
