### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by Smithx10** [stmcginnis/gofish#6]
How do I use Basic Auth with this library?

**Comment by ncode** [comment]
@Smithx10 you can check the example https://github.com/stmcginnis/gofish/blob/master/examples/query_sessions.go. It's using session tho, not basic auth.

**Comment by stmcginnis** [comment]
@Smithx10 - was that example helpful at all? We're still working through some things, so it would be great if you end up with a working example of basic auth, I'd love to add that as an example for others to follow.

**Comment by stmcginnis** [comment]
I'm hoping the updates since this was opened and the example provided have worked, so going to close this issue. If there are still problems, please let me know and we can try to fix it.
