### ISSUE TITLE
Several json unmarshal errors 

### ISSUE THREAD

**Issue by jenningsloy318** [stmcginnis/gofish#61]
Hi @stmcginnis , from my project [redfish-exporter](https://github.com/jenningsloy318/redfish_exporter) some users reported some json unmarshal error 

1. `Processor.Metrics` on Lenovo SR630, our definition is a `string`, but on his device it is a link 
```
{
    "ProcessorArchitecture": "x86",
    "Metrics": {
        "@odata.id": "/redfish/v1/Systems/1/Processors/1/ProcessorMetrics"
    },
```
2. `Memory.Location`, our definition is a `string`, but on his device it is a map 
```
    "Location": {
        "PartLocation": {
            "LocationType": "Slot",
            "ServiceLabel": "DIMM 5",
            "LocationOrdinalValue": 4
        }
    },
```
but from https://redfish.dmtf.org/redfish/mockups/v1/922#, we can use 
`MemoryLocation` for memory, instead of big changes of `Location` as it may exist else where 
```
    "MemoryLocation": {
        "Channel": 0,
        "MemoryController": 0,
        "Slot": 5,
        "Socket": 1
    },
```
currently `Location`  exist in `Chassis` and `Memory`

**Comment by stmcginnis** [comment]
Thanks @jenningsloy318. Looking at https://redfish.dmtf.org/schemas/v1/Processor.v1_7_0.json, it does appear Processor.Metrics should indeed be a link to a ProcessorMetrics object.

For Memory.Location, that definitely should be a map struct. From the docs, it says it should be a http://redfish.dmtf.org/schemas/v1/Resource.json#/definitions/Location. There is a separate property of the Memory of a MemoryLocation defined in https://redfish.dmtf.org/schemas/v1/Memory.v1_9_0.json. So those two properties look like they are different things.

MemoryLocation looks correct from the tested example JSON in https://github.com/stmcginnis/gofish/blob/master/redfish/memory_test.go. That is missing the Location property though.

So it does look like we need Processor.Metrics to be a link off to a ProcessMetrics object, and Memory.Location to a Location object.

I can try to get to this soon, but if you already have something and want to propose an update, that would be appreciated. I'm hoping to get to a few other updates this weekend.
