### ISSUE TITLE
PowerSupply.EfficiencyPercent is a float on Dell iDRAC

### ISSUE THREAD

**Issue by matejzero** [stmcginnis/gofish#68]
Hello,

I have a problem using https://github.com/jenningsloy318/redfish_exporter on Dell servers. It crashes because it can't unmarshal a float number into an integer field.

The problem is [EfficiencyPercent](https://github.com/stmcginnis/gofish/blob/4ab073c3a7c35c62e41bed37f55de48df4f6eb1d/redfish/power.go#L279), which is int. In my case, Redfish returns a float of `0.920000016689301`.

Looking at https://redfish.dmtf.org/schemas/v1/Power.v1_6_0.json, this number is suppose to be between 0 and 100 and unit is `%`. So the Dell's answer is not OK.

Is this something that could be fixed on the gofish side or should I try my luck with Dell?

**Comment by stmcginnis** [comment]
Thanks @matejzero. I think I've seen this elsewhere.

It might be worth reporting to Dell so they actually return the expected percentage. But we can update the field to be a float in Gofish so it can safely handle either way.

I can probably get to this soon, but feel free to propose a PR if you want to pick it up.

**Comment by matejzero** [comment]
Yes, I'm just writing a ticket to my Dell contact to get the issue fixed.

I'm no go coder, but will try to find some time and try my luck with a PR.

**Comment by matejzero** [comment]
After some thought, I think converting to float makes the field more useful, as redfish schema doesn't explicitly require integer and if Dell converts the output to percentage, it might still return 92,0000016689301%.

It will also give us/me an option to use the redfish_exporter without waiting for Dell to fix the issue, which might take time.

**Comment by stmcginnis** [comment]
Yeah, it looks like quite a few fields should probably be float. I got some clarification from someone working on Redfish. I can push up a change to convert everything over that is defined as a number in the schema rather than an integer.

**Comment by matejzero** [comment]
Will reply here instead of my fork.

Thanks for this quick fix. I'll rebuild the exporter today and report back.

**Comment by matejzero** [comment]
I don't get the error anymore, so I think it's fixed (exporter is still crashing, but the problem is elsewhere).

Thanks for a quick fix.
