### ISSUE TITLE
Add session management

### ISSUE THREAD

**Issue by mbethke** [stmcginnis/gofish#79]
I'm currently developing a Redfish-based Icinga check and would like to avoid spamming my iLO event log with "admin connection" entries - and I think this would go towards avoiding problems like in #75, too. The idea is to get a session token once and preserve it in-between plugin invocations by writing it to a session file, performing as new login only if the old one should have timed out. To do this, I'd need `APIClient.auth` exported though. At least that's how I hacked it for now - although that way I have to basically duplicate the second part of `gofish.Connect()`; perhaps it would be better to add an Auth member to `ClientConfig` and check in `Connect()` whether this or a username has been provided.

**Comment by stmcginnis** [comment]
Sounds reasonable. You mention having a hack in place to do this. Feel free to propose a PR with changes, and we can work through whether it fits or not. Thanks!

**Comment by mbethke** [comment]
Sorry, forgot to close this when you merged #83. All good now :)
