### ISSUE TITLE
Scripted import of schema

### ISSUE THREAD

**Issue by mike-pittelko** [stmcginnis/gofish#8]
Sean, I started looking at importing the full schema from dmtf.org for redfish. I cleaned up some issues with the .py script around legitimate identifiers in the output code, but source.go doesn't appear to match up well with the code already in the library. Is that expected, or does source.go need a bunch of updates?
Stuff yet to do:
1) lots of redeclaration issues (ex: OemActions, Links)
2) serialinterface and switch objects have some identifier issues on import to be dealt with

Oh and....small world, eh?

**Comment by stmcginnis** [comment]
Mike! Such a small world.

Yeah, the import tool is pretty primitive. It does require a bit of clean up after the initial code generation to get things in shape. I didn't want to spend too much time trying to handle every case, so it gets the basic framework of an object definition created, then I would reformat, update types, and clean up all of the duplicates and things that were not needed. I've also found the schema definitions themselves to have a few issues that require a little more thought/investigation.

I ran out of time working on the tooling, but if you are able to make any updates there to make that better, that could be very useful.

**Comment by mike-pittelko** [comment]
Everything but serialinterface and switch is syntactically correct at this point (cleans up spaces, dashes, slashes, etc), and super easy to update (run one script and it pulls in everything, runs the python/jinja2 stuff, drops it all in a directory, go fmt's it all. It's not terribly elegant, but it gets it done.  I'll get a pr in for what I've got, and keep messing with it a bit.
