### ISSUE TITLE
How to use the Settings object  

### ISSUE THREAD

**Issue by anupamaloke** [stmcginnis/gofish#80]
Resource annotations such as "@Redfish.Settings" provide additional information about a property or a resource.  See [here ](http://redfish.dmtf.org/schemas/DSP2046_2019.4.html#common-properties-Settings_v1.3.0)for more details.

I am writing an application using gofish to configure the server BIOS attributes. In order to do that, I need to find the `@Redfish.Settings` term in this resource, and if it is found, then makes requests to change BIOS settings by modifying the resource identified by the `@Redfish.Settings` term.

I see the Settings object defined in [types.go](https://github.com/stmcginnis/gofish/blob/master/common/types.go#L674), but it is not part of the [BIOS struct](https://github.com/stmcginnis/gofish/blob/master/redfish/bios.go#L55)

**Comment by stmcginnis** [comment]
Hi @anupamaloke. This isn't supported right now. I will need to look in to how this is supposed to be implemented.

The BIOS schema isn't very clear about this. It is only called out in the description of the Bios object:

> It is likely that a client finds the `@Redfish.Settings` term in this resource, and if it is found,
> the client makes requests to change BIOS settings by modifying the resource identified by
> the `@Redfish.Settings` term.

https://redfish.dmtf.org/schemas/v1/Bios.v1_1_1.json

**Comment by anupamaloke** [comment]
thanks @stmcginnis 
At present, I am testing this against the iDRACs, and the BIOS resource contains a settings object with an URI. This URI is different to the BIOS ```@odata.id```. At present, I am working around by hard-coding the URI for BIOS attribute PATCH operations by appending "Settings" string to the ```bios.ODataID``` attribute . 

```
    "@Redfish.Settings": {
        "@odata.context": "/redfish/v1/$metadata#Settings.Settings",
        "@odata.type": "#Settings.v1_2_1.Settings",
        "SettingsObject": {
            "@odata.id": "/redfish/v1/Systems/System.Embedded.1/Bios/Settings"
        },
        "SupportedApplyTimes": [
            "OnReset",
            "AtMaintenanceWindowStart",
            "InMaintenanceWindowOnReset"
        ]
    },
    "@odata.context": "/redfish/v1/$metadata#Bios.Bios",
    "@odata.id": "/redfish/v1/Systems/System.Embedded.1/Bios",
<Truncated for brevity>
```

**Comment by stmcginnis** [comment]
Thanks, I see that too. I think I understand how this is supposed to work now. Trying some things out now, so hopefully I will have something useful soon.

**Comment by stmcginnis** [comment]
Merged code that worked for me with the systems I had access to. Please try that out and let me know if there are any problems.
