### ISSUE TITLE
APIClient.Delete method just return error and not the HTTP response itself

### ISSUE THREAD

**Issue by mikeletux** [stmcginnis/gofish#85]
Hello Sean,

I've noticed that the *APIClient.Delete() method just returns an error interface saying if there was any issue with that call. The rest of HTTP method calls return also the a *http.Response object.
I think having also the *http.Response object returned from the Delete method is also very useful. Let me highlight that with an example. Please see the image below:

![deletemethod](https://user-images.githubusercontent.com/6768988/92742692-2af0a980-f380-11ea-8fd4-550a21845ab5.PNG)

I'm trying to get rid of a virtual disk. To do that, I need to perform a Delete onto /redfish/v1/Systems/\<ComputerSystem-Id>/Storage/\<Storage-Id>/Volumes.  

The operation is not done rightaway. In my case, the iDRAC, which is the controller that implements the RedfishAPI, creates a job. Then I need to record the job completion status, to see if that was ok or not.
In the Delete response headers, you can see the **Location** header, which is a link to that. I need to get that for checking the job status. Unfortunately in the current implementation I cannot get that because the Delete() method only returns an error.

Would you be open to accept a PR where apart from the error status also returns a *http.Response object?

Many thanks!
/Miguel

**Comment by stmcginnis** [comment]
I think that's a good idea @mikeletux. It's a change that may break some existing code, but I think you are correct that the current implementation is not right, and I think that should be changed to be consistent with the other calls.

**Comment by mikeletux** [comment]
Issue closed in #86
