### ISSUE TITLE
API or method to switch BMC mode btw dedicated mode and shared mode for dell server

### ISSUE THREAD

**Issue by leslie-qiwa** [stmcginnis/gofish#88]
I've been able to use this library to switch the mode by following HPE document: https://hewlettpackard.github.io/python-redfish-utility/#setting-active-ilo-nic.

Just wonder to know if it can do the same for dell server or not. Is there any document for that, or secret only?

**Comment by stmcginnis** [comment]
I'm not sure. If Dell exposes that in a way that can be updated through redfish, then it should be similar. There's nothing in the redfish protocol specifically for that, at least that I have seen.

**Comment by leslie-qiwa** [comment]
thanks for reply. I'll close it.
