### ISSUE TITLE
Way gofish.Service is retrieved

### ISSUE THREAD

**Issue by mikeletux** [stmcginnis/gofish#96]
Hello Sean,

Just writing you this issue because I wanted to know if it makes sense the change down below before going right away and create a PR.

The *Service* struct is retrieved once you have an APIClient created. Actually the field *Service* in API client is exportable and you get it like (where *client* is an instance of (*gofish.APIClient)):
~~~
service := client.Service
~~~

Since I'm thinking about the possibility of mocking the client and use it for testing across our Terraform provider project, I don't know if it makes sense the following:  

On common.Client interface, add a method like GetRootService() *gofish.Service (or whatever name that describes that better):
~~~
type Client interface {
	Get(url string) (*http.Response, error)
	Post(url string, payload interface{}) (*http.Response, error)
	Patch(url string, payload interface{}) (*http.Response, error)
	Put(url string, payload interface{}) (*http.Response, error)
	Delete(url string) (*http.Response, error)
        GetRootService()(*gofish.Service)
}
~~~

Then, on gofish.APIClient, make *Service* unexported, and create a method that retrieves it:
~~~
func (c *APIClient) GetRootService() *gofish.Service{
    return c.service
}
~~~

I think that would give us the possibility of using a mocked object across our code to test the different functions. So far is impossible because the client interface does not provide any signature to get the *Service* struct.

I know it is a significant change on the API, but I think it's worth the discussion 😄

**Comment by stmcginnis** [comment]
Hey @mikeletux - does the SetClient call work for your use case? That was added with a TestClient instance to enable unit testing.

https://github.com/stmcginnis/gofish/commit/0230c36235679e426f1f755d5b6232c97b0ee785

**Comment by mikeletux** [comment]
Hey Sean,
Sorry for coming back that later. Last weeks have been crazy for me.

I see what you proposed.
So far I've been passing the *common.Client* interface around as client.
From what you're proposing, I can pass a *Service* struct around, and set the client to a mocked one when testing.

Makes all the sense for me 😄 . What I was proposing was to do the other way around, but I think it doesn't pay off the effort.
Many thanks Sean!

/Miguel

**Comment by stmcginnis** [comment]
Awesome. Yeah, I could see it being useful either way. For the tests I was doing it was easiest to just inject the client fixture.

If you feel like working on other approaches, that works for me too. Thanks!

**Comment by stmcginnis** [comment]
I think this is resolved, but if not feel free to reopen or file a new issue.
